### ISSUE TITLE
v0.1 roadmap

### ISSUE THREAD

**Issue by yxonic** [ddyy-game/pecker#1]
### Investigation
- [ ] [toipe]: learn how it works.
- [ ] [crossterm]: learn about terminal manipulation.
- [ ] [clap]: learn about CLI arguments.
- [ ] [Terminal Anatomy]: learn about the mechanisms.

### Proof-of-Concept
- [ ] Display text and draw fingerings.
- [ ] Interactivity.
- [ ] Imitation exercise.
- [ ] Keyboard layout management.
- [ ] Statistics screen.

### Release

[toipe]: https://github.com/Samyak2/toipe
[crossterm]: https://docs.rs/crossterm/0.23.2/crossterm/
[clap]: https://github.com/clap-rs/clap
[Terminal Anatomy]: https://poor.dev/blog/terminal-anatomy/
